# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Triangle Fraternity at Michigan Technological University
description: > # this means to ignore newlines until "timezone:"
  Our commitment to building better men dates back more than 100 years to our beginnings at the University of Illinois, where Triangle was founded by 16 civil engineers who chose to lead in the classroom, on the campus, and within the community.
  Their choice was to form a group to support their needs and aspirations.
  Like Triangle’s Founders, we all face choices every day and the choices we make can affect the rest of our lives.
  Choosing the right fraternity is one of those choices – one that will have a profound impact on your time as a student, a career professional, and potential husband and father.
  If you are looking for a group to support your academic goals and graduation, provide leadership and social opportunities and a connection with thousands of prominent alumni in the fields of engineering, architecture, and science, talk to Triangle.
  Our members understand the challenges of a technical degree path and can be both a support system and valuable stepping stone on the path to a technical career.
timezone: America/Detroit
excerpt_separator: "<!-- excerpt -->"

# Social Media
email: triangle@mtu.edu
twitter_username: MTU_Triangle
instagram_username: mtu_triangle
github_username: trianglefraternitymtu
facebook_username: mtutriangle
twitch_username: trianglemtu
active_slack: mtutriangle
alumni_slack: mtutrianglealum
linkedin_id: 6976074

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num"

collections:
  events:
    output: true
    permalink: /:title
  spotlights:
    output: false
  docs:
    output: true

defaults:
  - scope:
      type: "events"
    values:
      layout: "event"
  - scope:
      type: "posts"
    values:
      permalink: /blog/:year/:month/:day/:title
  - scope:
      type: "spotlights"
    values:
      cover-image: http://placehold.it/750x450
      position: "Member"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
  - .travis.yml
  - .gitignore
  - LICENSE
